[package]
name = "parse"
version = "0.1.0"
edition = "2024"

[lib]
name = "parse"
path = "src/lib.rs"

[dependencies]
macros = { path = "../macros" }
thiserror = { workspace = true }
anyhow = { workspace = true }

