[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "lantern"
path = "src/main.rs"

[dependencies]
parse = { path = "../parse" }
runtime = { path = "../runtime" }
clap = { version = "4.5.31", features = ["derive"] }

