[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "lantern"
path = "src/main.rs"

[dependencies]
parse = { path = "../parse" }
flame = { path = "../flame" }
runtime = { path = "../runtime" }

