[package]
name = "ast"
version = "0.1.0"
edition = "2021"

[lib]
name = "ast"
path = "src/lib.rs"

[dependencies]
parse = { path = "../parse" }
macros = { path = "../macros" }
anyhow = { workspace = true }

